### ISSUE TITLE
Update and clarify documentation

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/CameraModelUtilsJS#2]
**TODO**
- [ ] Add docs for camera model object to the cahvore utils page
- [x] Add implementation for parameters to FrustumMesh contructor
- [x] Add implementation example / use to frustum mesh
- [x] Add implementation example / use to cahvore utils
