### ISSUE TITLE
Implementation adjustments

### ISSUE THREAD

**Issue by gkjohnson** [NASA-AMMOS/CameraModelUtilsJS#8]
**TODO**
- [x] nearDist / farDist to near / far in implementation
- [x] plane projection factor implementation
- [x] Consider merging the frustum implementations
- [ ] Consider moving the frustum logic purely to geometry
